### ISSUE TITLE
Shared Login page

### ISSUE THREAD

**Issue by Agotado** [dentych/ITTWEB#22] opened 2016-11-23 09:08 UTC
Multiple users are able to see eachother type in data on the login page

**Comment by dentych** [comment] 2016-11-23 21:24
Caused by BrowserSync, which is part of lite-server. Lite-server is a dev webserver, and shouldn't be used in production (which we kind of are :grin: )

**Comment by dentych** [comment] 2016-11-23 23:39
This issue is fixed fixed in d5b3f5d45ece5d4a981dae903a1f3f2f06fb5498

**Closed as completed** 2016-11-23 23:40 UTC
Labels: bug
